### ISSUE TITLE
Changing certain keybinds can spam logs

### ISSUE THREAD

**Issue by NiaSwift** [crazysmc/thorough-keybindings#4]
I noticed that if I go to

> `ESC -> Options... -> Controls... -> Key Binds...` and under `Modifier Keys`

and I change either the `Control 1` or `Control 2` to `Not Bound` (which is done by changing it to the `ESC` key). then I start to get the same error spammed a lot in the game logs whenever I do anything (moving in the game, pressing keys, typing in chat, etc.). This is what the error looks like:
```
[Render thread/ERROR]: ########## GL ERROR ##########
[Render thread/ERROR]: @ Render
[Render thread/ERROR]: 65539: Invalid key -1
```
Also, most actions in the game send that error, but clicking the middle mouse button makes it send the same but with `Pre Render` instead of `Render`.

And, if I change a different `Modifier Key` to `Not Bound`, but only ones that are set to a key used by a different keybind in the game (e.g. `Shift 1` since it uses `Left Shift` and so does the vanilla `Sneak` keybind), then it would also send that error in the game logs, but only once and only when I press `Back to Game` in the pause menu.

**Comment by crazysmc** [comment]
I did not expect someone to try to unbind these but you are right. The current implementation calls a GLFW function with an invalid argument if a key that is checked to be held down is set to nothing (-1).

I will see how to fix this, either by preventing it from being `Not Bound` or by using the default value in that case.

Oh btw don't worry that the default `Shift 1` "conflicts" with `Sneak` etc. It functions like normal to just keep them bound to the same key. Maybe I should make that more obvious on the settings page.

**Comment by NiaSwift** [comment]
> Oh btw don't worry that the default `Shift 1` "conflicts" with `Sneak` etc. It functions like normal to just keep them bound to the same key. Maybe I should make that more obvious on the settings page.

can you maybe make it so it doesn't show that it's conflicted? the reason i unbound it was cause it just annoyed me seeing the red thing in the menu, i already knew it doesn't actually break anything
